name: kyber_mod_manager
description: Kyber Mod Manager
publish_to: 'none'
version: 1.0.11

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.6
  dio: ^5.0.2
  uuid: ^3.0.5
  process_run: ^0.13.0
  sentry_flutter: ^7.7.0
  crypto: ^3.0.2
  window_manager: ^0.3.1
  windows_taskbar: ^1.1.0
  flutter_fadein: ^2.0.0
  url_launcher: ^6.1.5
  html: ^0.15.0
  intl: ^0.18.0
  flutter_platform_alert: ^0.4.0
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_hive_store: ^3.1.1
  package_info_plus: ^4.0.2
  system_info2: ^4.0.0
  auto_update: ^0.0.4
  flutter_markdown: ^0.6.10+3
  logging: ^1.0.2
  version: ^3.0.0
  flutter_bloc: ^8.0.1
  path: ^1.8.1
  path_provider: ^2.0.9
  desktop_drop: ^0.4.1
  archive: ^3.3.1
  auto_size_text: ^3.0.0
  fluent_ui: ^4.0.2
  system_tray: ^2.0.1
  tinycolor2: ^3.0.1
  http: ^1.0.0
  system_theme: ^2.0.0
  hive: ^2.0.6
  hive_flutter:
  json_annotation:
  flutter_acrylic: ^1.0.0+2
  puppeteer: ^3.0.0
  jiffy: ^6.2.1
  win32: ^5.0.3
  quiver: ^3.1.0
  ffi: ^1.0.0
  freezed_annotation:
  syncfusion_flutter_charts: ^21.2.9
  influxdb_client: ^2.5.0
  protocol_handler: ^0.1.4
  dynamic_env:
    path: 'packages/dynamic_env'
  flutter_translate:
    git:
      url: https://github.com/Jesway/Flutter-Translate.git
  bot_toast:
    git:
      url: https://github.com/MMMzq/bot_toast.git
  webview_windows:
    git:
      url: https://github.com/7reax/flutter-webview-windows
  dart_discord_rpc:
    git:
      url: https://github.com/alexmercerind/dart_discord_rpc.git
      ref: harmonoid
  linkable: ^3.0.1
  go_router: ^8.0.5
  file_selector: ^1.0.0

dependency_overrides:
  win32_registry:
    git:
      url: https://github.com/dart-windows/win32_registry.git
  ffi: ^2.0.0

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner:
  freezed:
  json_serializable:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.ico
    - assets/flags/
    - assets/i18n/
