name: kyber_mod_manager
description: Kyber Mod Manager
publish_to: 'none'
version: 1.0.5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_svg: ^1.0.3
  dio: ^4.0.0
  uuid: ^3.0.5
  process_run: ^0.12.3+2
  sentry_flutter: ^6.4.0
  dart_discord_rpc: ^0.0.2
  window_manager: ^0.2.1
  windows_taskbar: ^1.1.0
  flutter_fadein: ^2.0.0
  url_launcher: ^6.0.0
  intl: ^0.17.0
  dio_cache_interceptor: ^3.2.7
  dio_cache_interceptor_hive_store: ^3.1.1
  package_info_plus: ^1.4.2
  system_info2: ^2.0.3
  bot_toast: ^4.0.1
  auto_update: ^0.0.4
  flutter_markdown: ^0.6.9+1
  win32_registry: ^0.1.2
  logging: ^1.0.2
  version: ^2.0.0
  file_picker: ^4.3.3
  flutter_bloc: ^8.0.1
  path: ^1.8.0
  path_provider: ^2.0.9
  desktop_drop: ^0.3.3
  flutter_translate: ^4.0.2
  archive: ^3.2.1
  auto_size_text: ^3.0.0
  fluent_ui: ^3.9.1
  system_tray: ^0.1.0
  tinycolor2: ^2.0.0
  http: ^0.13.4
  system_theme: ^2.0.0
  hive: ^2.0.6
  hive_flutter:
  json_annotation:
  flutter_acrylic: ^1.0.0+2
  puppeteer: ^2.7.0
  jiffy: ^5.0.0
  win32: ^2.4.1
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation:

dev_dependencies:
  hive_generator: ^1.1.2
  build_runner:
  freezed:
  json_serializable:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.ico
    - assets/flags/
    - assets/i18n/
